/**
 * app/api/reactions/route.ts
 *
 * GET  /api/reactions?storyId=...[&guestId=...]  Fetch this learner's reaction to a story.
 * POST /api/reactions                           Record (or update) this learner's reaction to a story.
 *
 * Uses the `story_reactions` table. Who the learner is:
 *   - Signed-in user (registered OR Supabase anonymous guest): identified by the
 *     server-side session, never the request body. RLS policies ensure each user
 *     can only read, insert and update their own rows, and a UNIQUE (user_id, story_id)
 *     constraint keeps one reaction per story. is_guest mirrors user.is_anonymous.
 *   - No session at all (anonymous sign-ins disabled or failed): identified by a
 *     random guestId the browser keeps in localStorage. These rows are written with
 *     the service-role client (server only), with UNIQUE (guest_id, story_id).
 *     Because this path needs no login, it is rate limited: each network (hashed
 *     IP address) can create at most GUEST_LIMIT_MAX new guest reactions per
 *     GUEST_LIMIT_WINDOW_MINUTES. Updating an existing reaction is never limited.
 * Counts per story/reaction live in the `story_reaction_counts` view.
 */
import { createHash } from 'crypto'
import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'
import { adminClient } from '@/lib/supabase/admin'
import { isStoryReactionValue } from '@/lib/reactions'

// guestId must be a UUID generated by crypto.randomUUID() in the browser
const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i

function readGuestId(value: unknown): string | null {
  return typeof value === 'string' && UUID_RE.test(value.trim()) ? value.trim() : null
}

// Rate limit for session-less guests. Caravan tablets usually share one mall
// Wi-Fi IP, so keep this generous enough for a busy session.
const GUEST_LIMIT_MAX = 30
const GUEST_LIMIT_WINDOW_MINUTES = 10

/**
 * One-way hash of the caller's IP so raw IP addresses are never stored.
 * Salted with REACTION_IP_SALT (falls back to the service-role key, which is
 * already a server-only secret) so the hash can't be reversed by brute force.
 */
function hashRequestIp(request: NextRequest): string {
  const ip =
    request.headers.get('x-real-ip')?.trim() ||
    request.headers.get('x-forwarded-for')?.split(',')[0]?.trim() ||
    'unknown'
  const salt = process.env.REACTION_IP_SALT || process.env.SUPABASE_SERVICE_ROLE_KEY || ''
  return createHash('sha256').update(`${salt}:${ip}`).digest('hex')
}

// ─── GET /api/reactions ───────────────────────────────────────────────────────

export async function GET(request: NextRequest) {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()

  const storyId = request.nextUrl.searchParams.get('storyId')?.trim() ?? ''
  if (!storyId) {
    return NextResponse.json({ error: 'storyId is required.' }, { status: 400 })
  }

  // Session-less guest: look up by the browser's guestId instead
  const guestId = user ? null : readGuestId(request.nextUrl.searchParams.get('guestId'))
  if (!user && !guestId) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  const query = user
    ? supabase.from('story_reactions').select('reaction, updated_at').eq('user_id', user.id)
    : adminClient().from('story_reactions').select('reaction, updated_at').eq('guest_id', guestId!)

  const { data, error } = await query.eq('story_id', storyId).maybeSingle()

  if (error) {
    return NextResponse.json({ error: error.message }, { status: 500 })
  }

  const row = data as { reaction: string; updated_at: string } | null
  return NextResponse.json({
    reaction: row?.reaction ?? null,
    updatedAt: row?.updated_at ?? null,
  })
}

// ─── POST /api/reactions ──────────────────────────────────────────────────────

export async function POST(request: NextRequest) {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()

  const body = await request.json().catch(() => ({}))
  const storyId: string = typeof body.storyId === 'string' ? body.storyId.trim() : ''
  const reaction: unknown = typeof body.reaction === 'string' ? body.reaction.trim() : body.reaction
  const guestId = user ? null : readGuestId(body.guestId)

  if (!user && !guestId) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }
  if (!storyId) {
    return NextResponse.json({ error: 'storyId is required.' }, { status: 400 })
  }
  if (!isStoryReactionValue(reaction)) {
    return NextResponse.json({ error: 'Please pick a valid reaction.' }, { status: 400 })
  }

  // Session-less guest: only NEW reactions count toward the network's limit
  let ipHash: string | null = null
  if (!user) {
    ipHash = hashRequestIp(request)
    const admin = adminClient()
    const { data: existing, error: existingErr } = await admin
      .from('story_reactions')
      .select('id')
      .eq('guest_id', guestId!)
      .eq('story_id', storyId)
      .maybeSingle()
    if (existingErr) {
      return NextResponse.json({ error: existingErr.message }, { status: 500 })
    }
    if (!existing) {
      const since = new Date(Date.now() - GUEST_LIMIT_WINDOW_MINUTES * 60_000).toISOString()
      const { count, error: countErr } = await admin
        .from('story_reactions')
        .select('id', { count: 'exact', head: true })
        .eq('ip_hash', ipHash)
        .not('guest_id', 'is', null)
        .gte('created_at', since)
      if (countErr) {
        return NextResponse.json({ error: countErr.message }, { status: 500 })
      }
      if ((count ?? 0) >= GUEST_LIMIT_MAX) {
        return NextResponse.json(
          { error: 'Lots of reactions are coming from this network right now. Yours wasn’t saved, but you can keep going.' },
          { status: 429 }
        )
      }
    }
  }

  // One row per learner + story: insert the first time, update afterwards.
  // created_at keeps its original value on update; updated_at is refreshed.
  const updatedAt = new Date().toISOString()
  const { data: saved, error: upsertErr } = user
    ? await supabase
        .from('story_reactions')
        .upsert(
          {
            user_id: user.id,
            story_id: storyId,
            reaction,
            is_guest: user.is_anonymous ?? false,
            updated_at: updatedAt,
          },
          { onConflict: 'user_id,story_id' }
        )
        .select('reaction, created_at, updated_at')
        .single()
    : await adminClient()
        .from('story_reactions')
        .upsert(
          {
            guest_id: guestId,
            story_id: storyId,
            reaction,
            is_guest: true,
            ip_hash: ipHash,
            updated_at: updatedAt,
          } as any, // adminClient is untyped; same pattern as app/api/account
          { onConflict: 'guest_id,story_id' }
        )
        .select('reaction, created_at, updated_at')
        .single()

  if (upsertErr) {
    return NextResponse.json({ error: upsertErr.message }, { status: 500 })
  }

  const row = saved as { reaction: string; created_at: string; updated_at: string }
  return NextResponse.json({
    reaction: row.reaction,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
  })
}