'use client'

import { useState } from 'react'
import { ArrowLeft, ArrowRight, BookOpen, Check, ChevronRight, CircleHelp, Gift, Home, LockKeyhole, Menu, QrCode, Sparkles, Trophy, UserRound, X } from 'lucide-react'

const mascot = 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/u%201-iNRGaghtYtdeXSHFa2XQPl2ryeu5Fm.png'
const stories = [
  { title: 'Study Buddy', subtitle: 'Build a helpful study companion', color: '#79a8ff', image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Untitled%20design%20%2889%29%201-VY50vMtptXr0tOsB2AUUCKt4I96OmQ.png' },
  { title: 'Train Your Bot', subtitle: 'Learn how prompts guide AI', color: '#ff694d', image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Untitled%20design%20%2886%29%201-rBSaIUsON4qoxIWreizUBniwa2lTVe.png' },
  { title: 'Trust the System?', subtitle: 'Explore responsible AI choices', color: '#7fd3af', image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Untitled%20design%20%2887%29%201-WlTU4dT7vim0CGF0VihadqQ7EvoMrF.png' },
]
const scenes = ['The discovery', 'The question', 'The choice', 'The result']

type Screen = 'launch' | 'start' | 'auth' | 'profile' | 'stories' | 'story' | 'archive' | 'dashboard' | 'rewards'

export default function Page() {
  const [screen, setScreen] = useState<Screen>('launch')
  const [authMode, setAuthMode] = useState<'signup' | 'signin'>('signup')
  const [guestStory, setGuestStory] = useState<number | null>(null)
  const [story, setStory] = useState(0)
  const [scene, setScene] = useState(0)
  const [menu, setMenu] = useState(false)
  const [profileCreated, setProfileCreated] = useState(false)
  const [claimed, setClaimed] = useState(false)

  const go = (next: Screen) => { setScreen(next); setMenu(false) }
  const chooseStory = (index: number) => { if (guestStory === null || guestStory === index || profileCreated) { setStory(index); setScene(0); go('story') } }

  return <div className="app-shell">
    {screen !== 'launch' && <header className="topbar"><button className="brand" onClick={() => go('launch')}><span className="brand-mark">AI</span><span>for <b>ALL</b></span></button><div className="header-actions"><button className="icon-button" aria-label="Help"><CircleHelp size={20}/></button><button className="icon-button" aria-label="Open menu" onClick={() => setMenu(!menu)}>{menu ? <X size={20}/> : <Menu size={20}/>}</button></div></header>}
    {menu && <div className="menu-popover"><button onClick={() => go('dashboard')}>My profile</button><button onClick={() => go('archive')}>My archive</button><button onClick={() => go('rewards')}>Rewards</button><a href="/admin">Admin portal</a></div>}
    <main className={screen === 'launch' ? 'main-content launch-wrap' : 'main-content'}>
      {screen === 'launch' && <Launch onStart={() => go('start')} />}
      {screen === 'start' && <Start onAuth={(mode) => { setAuthMode(mode); go('auth') }} onGuest={() => go('stories')} />}
      {screen === 'auth' && <Auth mode={authMode} onMode={setAuthMode} onDone={() => { setProfileCreated(true); go('profile') }} />}
      {screen === 'profile' && <ProfileSetup onDone={() => { setProfileCreated(true); go('dashboard') }} />}
      {screen === 'stories' && <Stories guestStory={guestStory} setGuestStory={setGuestStory} onChoose={chooseStory} onBack={() => go('start')} />}
      {screen === 'story' && <Story title={stories[story].title} scene={scene} setScene={setScene} onBack={() => go('stories')} onFinish={() => go('dashboard')} />}
      {screen === 'dashboard' && <Dashboard onStories={() => go('stories')} onArchive={() => go('archive')} />}
      {screen === 'archive' && <Archive onBack={() => go('dashboard')} />}
      {screen === 'rewards' && <Rewards claimed={claimed} setClaimed={setClaimed} onBack={() => go('dashboard')} />}
    </main>
    {!['launch','start','auth','profile','story'].includes(screen) && <BottomNav screen={screen} onHome={() => go('dashboard')} onStories={() => go('stories')} onArchive={() => go('archive')} onProfile={() => go('dashboard')} />}
  </div>
}

function Launch({ onStart }: { onStart: () => void }) { return <section className="launch-page"><div className="launch-copy"><div className="brand launch-brand"><span className="brand-mark">AI</span><span>for <b>ALL</b></span></div><h1>Learn AI<br/><em>through</em><br/>stories</h1><button className="launch-button" onClick={onStart}>start here <ArrowRight size={16}/></button></div><img className="launch-mascot" src={mascot} alt="AI for ALL mascot"/></section> }
function Start({ onAuth, onGuest }: { onAuth: (mode: 'signup'|'signin') => void; onGuest: () => void }) { return <section className="onboarding-page"><p className="kicker">AI FOR ALL</p><h2>Let&apos;s get<br/><span>you started</span></h2><p>Learn how AI works through quick, interactive stories. No experience needed.</p><button className="primary-button" onClick={() => onAuth('signup')}>Sign up</button><button className="secondary-button" onClick={() => onAuth('signin')}>Log in</button><button className="text-button" onClick={onGuest}>Continue as guest</button><small>Accessibility and assistance</small><img src="https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Untitled%20design%20%2883%29%201-GfWInwvd4aNMb16ANSTiCafiREv6io.png" alt="Friendly mascot"/></section> }
function Auth({ mode, onMode, onDone }: { mode: 'signup'|'signin'; onMode: (mode: 'signup'|'signin') => void; onDone: () => void }) { return <section className="auth-page"><div className="auth-art"><img src={mascot} alt="AI for ALL mascot"/><h2>{mode === 'signup' ? 'Ready to Learn AI?' : 'Hey There, You’re Back!'}</h2></div><div className="auth-form"><p className="kicker">{mode === 'signup' ? 'CREATE YOUR ACCOUNT' : 'WELCOME BACK'}</p><label>Your Name<input placeholder="Enter your name"/></label><label>Email<input type="email" placeholder="you@example.com"/></label><label>Password<input type="password" placeholder="••••••••"/></label><button className="primary-button" onClick={onDone}>{mode === 'signup' ? 'I’m Ready' : 'Login'} <ChevronRight size={17}/></button><button className="text-button" onClick={() => onMode(mode === 'signup' ? 'signin' : 'signup')}>{mode === 'signup' ? 'Already have an account? Sign in' : 'Need an account? Sign up'}</button></div></section> }
function ProfileSetup({ onDone }: { onDone: () => void }) { return <section className="profile-setup"><p className="kicker">PROFILE CREATED</p><h2>You&apos;re all set, <span>Daniel!</span></h2><p>Your profile is ready. Your stories, and progress can now be saved.</p><img src="https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Untitled%20design%20%2892%29%201-aiKRFyLKe0eeImvRr0FlBHR6wrS7WD.png" alt="Mascot celebrating"/><button className="primary-button" onClick={onDone}>Continue</button></section> }
function Stories({ guestStory, setGuestStory, onChoose, onBack }: { guestStory: number | null; setGuestStory: (value: number) => void; onChoose: (index: number) => void; onBack: () => void }) { return <section className="story-select page-section"><BackButton onClick={onBack}/><div className="section-heading"><p className="kicker">STORIES</p><h2>Select a story</h2><p>{guestStory === null ? 'Choose one story to begin as a guest. Sign up to unlock them all.' : `Guest mode: ${stories[guestStory].title} is your free story.`}</p></div><div className="story-carousel">{stories.map((item, index) => { const locked = guestStory !== null && guestStory !== index; return <button key={item.title} className={`story-tile ${locked ? 'is-locked' : ''}`} style={{ background: item.color }} onClick={() => onChoose(index)} disabled={locked}><div><strong>{item.title}</strong><small>{item.subtitle}</small></div>{locked ? <LockKeyhole size={17}/> : <ArrowRight size={17}/>}<img src={item.image} alt="Story character"/></button>})}</div>{guestStory === null && <p className="guest-note"><Sparkles size={14}/> Once you choose, the other stories stay locked in guest mode.</p>}</section> }
function Story({ title, scene, setScene, onBack, onFinish }: { title: string; scene: number; setScene: (value: number) => void; onBack: () => void; onFinish: () => void }) { const done = scene === scenes.length - 1; return <section className="story-page"><div className="story-toolbar"><button className="back-button" onClick={onBack}><ArrowLeft size={18}/> Stories</button><span className="story-progress">{scene + 1} / {scenes.length}</span></div><div className="progress-track"><span style={{ width: `${((scene + 1) / scenes.length) * 100}%` }}/></div><div className="scene-card"><div className="scene-art"><div className="ai-orb">●</div><span>Study with AI</span></div><div className="scene-copy"><p className="kicker">{title.toUpperCase()} · SCENE {scene + 1}</p><h2>{scenes[scene]}</h2><p>{scene === 0 ? 'Meet your AI guide. It listens, learns, and gets better when you explain what you need.' : scene === 1 ? 'A good prompt gives context and asks clearly for what you want.' : scene === 2 ? 'Choose the response that feels most useful and responsible.' : 'You made a thoughtful choice. Keep asking questions and checking the result.'}</p>{done ? <button className="primary-button" onClick={onFinish}>Finish story <Check size={18}/></button> : <button className="choice-button selected" onClick={() => setScene(scene + 1)}>Continue <ChevronRight size={18}/></button>}</div></div></section> }
function Dashboard({ onStories, onArchive }: { onStories: () => void; onArchive: () => void }) { return <section className="page-section dashboard-page"><div className="dashboard-intro"><div><p className="kicker">PROFILE</p><h2>Hi, Michael!</h2><p>Keep exploring and building your AI toolkit.</p></div><div className="avatar"><UserRound size={26}/></div></div><div className="dashboard-stats"><div><strong>3</strong><small>Stories</small></div><div><strong>2</strong><small>Badges</small></div><div><strong>48<span> min</span></strong><small>This week</small></div></div><button className="dashboard-action" onClick={onStories}><BookOpen size={24}/><strong>Explore stories</strong><span>Continue learning <ArrowRight size={16}/></span></button><div className="goal-card"><div><span className="tag">GOAL BOARD</span><h3>Understand AI Basics</h3><p>1 of 4 stories completed</p></div><div className="goal-ring">25%</div></div><div className="archive-heading"><h3>Completed stories</h3><button className="text-button" onClick={onArchive}>View all</button></div><div className="mini-archive"><div>Study Buddy <Check size={16}/></div><div>Train Your Bot <Check size={16}/></div></div></section> }
function Archive({ onBack }: { onBack: () => void }) { return <section className="page-section archive-page"><BackButton onClick={onBack}/><div className="section-heading"><p className="kicker">MY PROFILE</p><h2>My Archive</h2><p>Stories you have completed and can revisit anytime.</p></div><input className="archive-search" placeholder="⌕  Search stories"/>{['Study Buddy','Train Your Bot','Trust the System?','What is AI?','How AI Helps Us'].map((title, i) => <div className={`archive-stack stack-${i}`} key={title}><strong>{title}</strong><span>100%</span><small>{i < 2 ? 'Completed May 18, 2026' : 'Completed'}</small><ChevronRight size={17}/></div>)}</section> }
function Rewards({ claimed, setClaimed, onBack }: { claimed: boolean; setClaimed: (value: boolean) => void; onBack: () => void }) { return <section className="page-section rewards-page"><BackButton onClick={onBack}/><div className="section-heading"><p className="kicker">MY REWARDS</p><h2>Celebrate your wins</h2></div><div className="badge-card"><div className="badge-medal"><Trophy size={30}/></div><div><span className="tag">EARNED</span><h3>Curious Explorer</h3><p>Completed your first AI story.</p></div><Check className="badge-check" size={22}/></div><div className="reward-row"><div className="reward-symbol"><QrCode size={22}/></div><div><strong>Learning kit</strong><p>Claim your reward from your facilitator.</p></div><button className="outline-button" onClick={() => setClaimed(true)}>{claimed ? 'Claimed' : 'Claim'}</button></div>{claimed && <div className="claim-modal"><div className="qr-box"><QrCode size={74}/></div><h3>Ready to claim</h3><p>Show this code to your facilitator.</p></div>}</section> }
function BottomNav({ onHome, onStories, onArchive, onProfile, screen }: { onHome: () => void; onStories: () => void; onArchive: () => void; onProfile: () => void; screen: Screen }) { return <nav className="bottom-nav"><button className={screen === 'dashboard' ? 'active' : ''} onClick={onHome}><Home size={19}/><span>Home</span></button><button className={screen === 'stories' ? 'active' : ''} onClick={onStories}><BookOpen size={19}/><span>Goal Board</span></button><button className={screen === 'archive' ? 'active' : ''} onClick={onArchive}><Gift size={19}/><span>Completed Stories</span></button><button className={screen === 'dashboard' ? 'active' : ''} onClick={onProfile}><UserRound size={19}/><span>Profile</span></button></nav> }
function BackButton({ onClick }: { onClick: () => void }) { return <button className="back-button page-back" onClick={onClick}><ArrowLeft size={18}/> Back</button> }
